# Workflow-CI/MLProject/conda.yaml

name: mlproject-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.18 # Atau versi Python yang Anda gunakan
  - pip
  - pip:
    - mlflow==3.1.0
    - pandas==2.2.2
    - numpy==2.0.2
    - scikit-learn==1.6.1
    - pyngrok==7.2.11
    - dagshub===0.3.3
