# Workflow-CI/.github/workflows/ci_retrain.yml

name: CI - Retrain ML Model 

on:
  push:
    branches:
      - main 
    paths:
      - 'MLProject/modelling.py' 
      - 'MLProject/conda.yaml'   
      - 'MLProject/MLProject'   
      - 'MLProject/telco_churn_preprocessing/**' 
  workflow_dispatch: 

jobs:
  retrain_model:
    runs-on: ubuntu-latest

    permissions:
      contents: write 
      id-token: write 

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 
        
    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml 
        activate-environment: mlproject-env 
        auto-activate-base: false 

    - name: Install MLflow and DagsHub client 
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate mlproject-env
        
        python -m pip install --upgrade pip
        pip install mlflow==3.1.0 dagshub==0.5.10

        python -c "import dagshub; print('DagsHub version:', dagshub.__version__)"

    - name: Configure DagsHub MLflow Tracking 
      run: |
        echo "MLFLOW_TRACKING_URI=https://dagshub.com/hyrahmaaa/Workflow-CI.mlflow" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_USERNAME=hyrahmaaa" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
 
        echo "DAGSHUB_REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

    - name: Run MLflow Project (Model Retraining)
      run: |
        set -e 
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate mlproject-env
        
        echo "=== Executing mlflow run MLProject/ Directly ==="
        mlflow run MLProject/  
        
        echo "=== mlflow run command finished ==="
      env: 
        MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}

    - name: Debug - Find Model Files  
      run: |
        echo "=== DEBUGGING AFTER MLFLOW RUN ==="
        find . -name "*.pkl" -o -name "*.joblib" 2>/dev/null || echo "No model files found"
        echo "=== MLFLOW RUNS FOLDER ==="
        ls -la mlruns/ 2>/dev/null || echo "No mlruns folder"
        find mlruns/ -name "artifacts" 2>/dev/null || echo "No artifacts in mlruns"
        echo "=== CURRENT DIRECTORY ==="
        ls -la
    
    - name: Check Artifacts
      run: |
        ls -la artifacts/
        ls -la artifacts/model/ || echo "Model folder not found"
    
    - name: Upload Model Artifact to DagsHub
      env:
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python -c "
        import dagshub
        import os
        dagshub.auth.add_app_password(token='${{ secrets.DAGSHUB_TOKEN }}')
        dagshub.upload_file(
            repo_url='https://dagshub.com/hyrahasan/workflow-CI',
            local_path='artifacts/model',
            remote_path='model',
            message='Model artifact from CI retraining'
        )

    - name: Upload Model Artifact to DagsHub (Alternative Method)
      if: failure() && env.MLFLOW_RUN_ID != ''
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate mlproject-env
        
        # Gunakan Python script sebagai fallback
        python << 'EOF'
        import os
        import dagshub
        
        # Setup credentials
        os.environ['DAGSHUB_USER_TOKEN'] = '${{ env.MLFLOW_TRACKING_PASSWORD }}'
        
        try:
            # Initialize DagsHub repo
            dagshub.init(
                repo_owner='${{ env.MLFLOW_TRACKING_USERNAME }}',
                repo_name='${{ env.DAGSHUB_REPO_NAME }}',
                mlflow=True
            )
            
            # Upload using Python API
            dagshub.upload_files(
                local_path='mlruns/0/${{ env.MLFLOW_RUN_ID }}/artifacts/model',
                remote_path='artifacts/model',
                commit_message='Model artifact from CI retraining ${{ env.MLFLOW_RUN_ID }}'
            )
            print("Model artifact uploaded successfully!")
            
        except Exception as e:
            print(f"Upload failed: {e}")
            # Fallback: just log the model location
            print(f"Model saved locally at: mlruns/0/${{ env.MLFLOW_RUN_ID }}/artifacts/model")
        EOF
      env:
        MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}

    - name: Commit processed data 
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git pull origin main --rebase # Ambil perubahan terbaru dari remote sebelum push

        git add . # Tambahkan semua file yang berubah/baru (termasuk mlruns/)

        git commit -m "Automated: Model retraining results updated" || true # Commit perubahan
        git push # Push perubahan ke remote
