# Workflow-CI/.github/workflows/ci_retrain.yml

name: CI - Retrain ML Model

on:
  push:
    branches:
      - main
    paths:
      - 'MLProject/modelling_tuning.py'
      - 'MLProject/conda.yaml'
      - 'MLProject/MLProject'
      - 'MLProject/telco_churn_preprocessing/**'
  workflow_dispatch:

jobs:
  retrain_model:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      DAGSHUB_REPO_NAME: Workflow-CI

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda with Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          auto-activate-base: true
          activate-environment: mlproject-env
          environment-file: MLProject/conda.yaml

      - name: Install MLflow and DagsHub client
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.1.0 dagshub==0.5.10

      - name: Configure DagsHub MLflow Tracking
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/hyrahmaaa/${{ env.DAGSHUB_REPO_NAME }}.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=hyrahmaaa" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run MLflow Project (Model Retraining)
        run: |
          RUN_ID=$(mlflow run MLProject/ 2>&1 | grep "Running command" | grep -oP "run with ID '\K[^']+" | tail -n 1)
          echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "MLflow run initiated with ID: $RUN_ID"
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}
            
      - name: Commit processed data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --rebase
          git add .
          git commit -m "Automated: Model retraining results updated" || true
          git push
