# Workflow-CI/.github/workflows/ci_retrain.yml

name: CI - Retrain ML Model # Nama workflow Anda

on:
  push:
    branches:
      - main # Ganti dengan nama branch utama Anda jika berbeda (misal: master)
    paths:
      - 'MLProject/modelling.py' # Trigger jika kode model berubah
      - 'MLProject/conda.yaml'   # Trigger jika lingkungan Conda berubah
      - 'MLProject/MLProject'    # Trigger jika konfigurasi project MLflow berubah
      - 'MLProject/telco_churn_preprocessing/**' # Trigger jika data preprocessing berubah
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow secara manual dari UI GitHub

jobs:
  retrain_model:
    runs-on: ubuntu-latest # Runner yang akan menjalankan job

    permissions:
      contents: write # Diperlukan untuk push commit ke repo
      id-token: write # Diperlukan untuk beberapa integrasi (misal, OIDC)

    steps:
    - name: Checkout repository # Checkout kode dari repositori
      uses: actions/checkout@v4

    # Menggunakan action 'setup-python' untuk menginstal Python dasar
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Pastikan versi ini cocok dengan yang di conda.yaml Anda

    # Menggunakan action 'conda-incubator/setup-miniconda' untuk setup Conda
    # Ini akan membuat dan mengaktifkan lingkungan dari conda.yaml Anda
    - name: Set up Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml # Path ke file conda.yaml Anda
        activate-environment: mlproject-env # Nama environment dari conda.yaml Anda (harus sama dengan name di conda.yaml)
        auto-activate-base: false # Hindari aktivasi base environment secara otomatis

    - name: Install MLflow and DagsHub client # Instal pustaka di lingkungan yang aktif
      run: |
        # Pastikan Conda diinisialisasi untuk shell ini dan lingkungan diaktifkan
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate mlproject-env
        
        python -m pip install --upgrade pip
        # Instal versi spesifik untuk konsistensi
        pip install mlflow==3.1.0 dagshub==0.5.10
        
        # Verifikasi instalasi dagshub
        python -c "import dagshub; print('DagsHub version:', dagshub.__version__)"

    - name: Configure DagsHub MLflow Tracking # Menyiapkan variabel lingkungan untuk DagsHub
      run: |
        echo "MLFLOW_TRACKING_URI=https://dagshub.com/hyrahmaaa/Workflow-CI.mlflow" >> $GITHUB_ENV # <--- GANTI USERNAME DAN REPO ANDA
        echo "MLFLOW_TRACKING_USERNAME=hyrahmaaa" >> $GITHUB_ENV # <--- GANTI USERNAME ANDA
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV # <--- GUNAKAN GITHUB SECRET ANDA
        # Simpan nama repositori DagsHub Anda (sama dengan nama repo GitHub)
        echo "DAGSHUB_REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

    - name: Run MLflow Project (Model Retraining) # Menjalankan MLflow Project dan menangkap Run ID
      run: |
        # Pastikan Conda diinisialisasi untuk shell ini dan lingkungan diaktifkan
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate mlproject-env
        
        # Jalankan MLflow Project. Ini akan memanggil modelling.py dan mencatat run.
        # Tangkap RUN_ID yang dihasilkan oleh mlflow run. Ini adalah metode yang lebih robust.
        RUN_ID=$(mlflow run MLProject/ 2>&1 | grep "Running command" | grep -oP "run with ID '\K[^\']+" | tail -n 1)
        
        echo "MLFLOW_RUN_ID=$RUN_ID" >> $GITHUB_ENV # Simpan RUN_ID sebagai environment variable
        echo "MLflow run initiated with ID: $RUN_ID" # Pesan debugging
      env: # Pastikan variabel DagsHub juga tersedia di step ini
        MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}
        
    - name: Upload Model Artifact to DagsHub # Langkah untuk mengunggah artefak ke DagsHub
      # Hanya jalankan ini jika MLflow_RUN_ID berhasil ditangkap
      if: env.MLFLOW_RUN_ID != ''
      run: |
        # Pastikan Conda diinisialisasi untuk shell ini dan lingkungan diaktifkan
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate mlproject-env
        
        # Pastikan dagshub terinstal di environment ini
        pip install dagshub==0.5.10
        
        # SOLUSI 1: Gunakan dagshub sebagai command langsung (lebih reliable)
        dagshub artifact upload \
          --repo-url "https://dagshub.com/${{ env.MLFLOW_TRACKING_USERNAME }}/${{ env.DAGSHUB_REPO_NAME }}.git" \
          --run-id ${{ env.MLFLOW_RUN_ID }} \
          --path-on-dagshub "model" \
          --message "Model artifact from CI retraining ${{ env.MLFLOW_RUN_ID }}" \
          "mlruns/0/${{ env.MLFLOW_RUN_ID }}/artifacts/model"
          
        # JIKA SOLUSI 1 GAGAL, uncomment solusi 2 di bawah dan comment solusi 1
        # SOLUSI 2: Gunakan Python script untuk upload
        # python -c "
        # import dagshub
        # dagshub.upload_files(
        #     repo_url='https://dagshub.com/${{ env.MLFLOW_TRACKING_USERNAME }}/${{ env.DAGSHUB_REPO_NAME }}.git',
        #     local_path='mlruns/0/${{ env.MLFLOW_RUN_ID }}/artifacts/model',
        #     remote_path='artifacts/model',
        #     commit_message='Model artifact from CI retraining ${{ env.MLFLOW_RUN_ID }}'
        # )"
        
      env: # Pastikan variabel DagsHub juga tersedia di step ini
        MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}

    - name: Upload Model Artifact to DagsHub (Alternative Method) # Metode alternatif jika yang pertama gagal
      # Hanya jalankan ini jika step sebelumnya gagal
      if: failure() && env.MLFLOW_RUN_ID != ''
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate mlproject-env
        
        # Gunakan Python script sebagai fallback
        python << 'EOF'
        import os
        import dagshub
        
        # Setup credentials
        os.environ['DAGSHUB_USER_TOKEN'] = '${{ env.MLFLOW_TRACKING_PASSWORD }}'
        
        try:
            # Initialize DagsHub repo
            dagshub.init(
                repo_owner='${{ env.MLFLOW_TRACKING_USERNAME }}',
                repo_name='${{ env.DAGSHUB_REPO_NAME }}',
                mlflow=True
            )
            
            # Upload using Python API
            dagshub.upload_files(
                local_path='mlruns/0/${{ env.MLFLOW_RUN_ID }}/artifacts/model',
                remote_path='artifacts/model',
                commit_message='Model artifact from CI retraining ${{ env.MLFLOW_RUN_ID }}'
            )
            print("Model artifact uploaded successfully!")
            
        except Exception as e:
            print(f"Upload failed: {e}")
            # Fallback: just log the model location
            print(f"Model saved locally at: mlruns/0/${{ env.MLFLOW_RUN_ID }}/artifacts/model")
        EOF
      env:
        MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        MLFLOW_TRACKING_USERNAME: ${{ env.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ env.MLFLOW_TRACKING_PASSWORD }}

    - name: Commit processed data # Menyimpan kembali perubahan (termasuk folder mlruns/)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git pull origin main --rebase # Ambil perubahan terbaru dari remote sebelum push

        git add . # Tambahkan semua file yang berubah/baru (termasuk mlruns/)

        git commit -m "Automated: Model retraining results updated" || true # Commit perubahan
        git push # Push perubahan ke remote
